import React from "react";

const GameRoom = () => {
  // TODO IMPLEMENT ROLES IN GAME THAT NARRATOR CAN SEE AND KILL/BRING BACK TO LIFE AND LATER ON IT SHOULD LIVE UPDATE
  // OTHER DEVICES BY SENDING A WEBHOOK. ONCE EVERYONE HAS DIED, WILL KICK OFF WEBHOOK TO SEND TO OTHER DEVICES NOTIFYING THEM
  // SHOULD ALSO HAVE A QUICK START BUTTON TO START A NEW GAME WITH THE CURRENT PLAYER LIST
  return <div>GameRoom</div>;
};

export default GameRoom;
